export default [
  {
    id: 381632,
    secret: 'BdXJ202GdS-nRror',
    quote: {
      id: 447412,
      title: null,
      status: {
        id: 45,
        type: 'quote_status',
        type_display: 'Quote Status',
        code: 'app',
        label: 'Approved',
        sequence: 10.0,
      },
      order: {
        id: 227816,
        product: {
          id: 105,
          name: 'Fence Installation',
          short_name: 'Fence',
          slug: 'fence-replacement',
          is_active: true,
        },
        house: {
          id: 203948,
          address: {
            formatted_address: '307 Palo Alto Ave, Palo Alto, CA 94301, USA',
            zip_code: '94301',
            latitude: 37.4494031,
            longitude: -122.1672177,
          },
          is_hidden: false,
          has_active_order: true,
          customer: {
            id: 194602,
            user_id: 199284,
            gid: 'D8tvLSHsoHAW4G2x',
            full_name: 'Elaine Schuppe',
            email: 'test+Jennings_Purdy97@hotmail.com',
            phone_number: null,
            main_address: {
              formatted_address: '307 Palo Alto Ave, Palo Alto, CA 94301, USA',
              zip_code: '94301',
              latitude: 37.4494031,
              longitude: -122.1672177,
            },
          },
        },
        customer_deal_status: 'Approved',
        sales_rep: null,
        project_manager: {
          id: 2132,
          full_name: 'Jose Andres Ortiz Zea',
          phone_number: '(533) 613-8135',
          email: 'andres.ortiz@ergeon.com',
        },
      },
      preview_image: null,
      total_price: '72.00',
      sent_to_customer_at: '2022-09-15T06:11:19.582201-07:00',
    },
  },
  {
    id: 381633,
    secret: 'YEIv5qCsYe6ohr0l',
    quote: {
      id: 447413,
      title: null,
      status: {
        id: 45,
        type: 'quote_status',
        type_display: 'Quote Status',
        code: 'app',
        label: 'Cancelled',
        sequence: 10.0,
      },
      order: {
        id: 227816,
        product: {
          id: 105,
          name: 'Fence Installation',
          short_name: 'Fence',
          slug: 'fence-replacement',
          is_active: true,
        },
        house: {
          id: 203948,
          address: {
            formatted_address: '307 Palo Alto Ave, Palo Alto, CA 94301, USA',
            zip_code: '94301',
            latitude: 37.4494031,
            longitude: -122.1672177,
          },
          is_hidden: false,
          has_active_order: true,
          customer: {
            id: 194602,
            user_id: 199284,
            gid: 'D8tvLSHsoHAW4G2x',
            full_name: 'Elaine Schuppe',
            email: 'test+Jennings_Purdy97@hotmail.com',
            phone_number: null,
            main_address: {
              formatted_address: '307 Palo Alto Ave, Palo Alto, CA 94301, USA',
              zip_code: '94301',
              latitude: 37.4494031,
              longitude: -122.1672177,
            },
          },
        },
        customer_deal_status: 'Approved',
        sales_rep: null,
        project_manager: {
          id: 2132,
          full_name: 'Jose Andres Ortiz Zea',
          phone_number: '(533) 613-8135',
          email: 'andres.ortiz@ergeon.com',
        },
      },
      preview_image: null,
      total_price: '72.00',
      sent_to_customer_at: '2022-09-15T06:11:57.649759-07:00',
    },
  },
  {
    id: 381631,
    secret: 'FvlZxmSzjFWlke7i',
    quote: {
      id: 447411,
      title: null,
      status: {
        id: 43,
        type: 'quote_status',
        type_display: 'Quote Status',
        code: 'new',
        label: 'Draft',
        sequence: 1.0,
      },
      order: {
        id: 227816,
        product: {
          id: 105,
          name: 'Fence Installation',
          short_name: 'Fence',
          slug: 'fence-replacement',
          is_active: true,
        },
        house: {
          id: 203948,
          address: {
            formatted_address: '307 Palo Alto Ave, Palo Alto, CA 94301, USA',
            zip_code: '94301',
            latitude: 37.4494031,
            longitude: -122.1672177,
          },
          is_hidden: false,
          has_active_order: true,
          customer: {
            id: 194602,
            user_id: 199284,
            gid: 'D8tvLSHsoHAW4G2x',
            full_name: 'Elaine Schuppe',
            email: 'test+Jennings_Purdy97@hotmail.com',
            phone_number: null,
            main_address: {
              formatted_address: '307 Palo Alto Ave, Palo Alto, CA 94301, USA',
              zip_code: '94301',
              latitude: 37.4494031,
              longitude: -122.1672177,
            },
          },
        },
        customer_deal_status: 'Approved',
        sales_rep: null,
        project_manager: {
          id: 2132,
          full_name: 'Jose Andres Ortiz Zea',
          phone_number: '(533) 613-8135',
          email: 'andres.ortiz@ergeon.com',
        },
      },
      preview_image: null,
      total_price: '0.00',
      sent_to_customer_at: null,
    },
  },
];
