const mapping = require('./mapping');
import {parseSheet} from './parsing';

describe('Cities', () => {
  const citiesTestData = [
    [
      "address",
      "license 1",
      "license 2",
      "license 3",
      "license URL",
      "product",
      "county",
      "city",
      "state",
      "header title",
      "header bullet 1",
      "header bullet 2",
      "header bullet 3",
      "header bullet 4",
      "phone ",
      "thumbtack score",
      "yelp score",
      "google score",
      "angi score",
      "bbb score",
      "review 1",
      "poster name 1",
      "call out 1",
      "project address 1",
      "listing url 1",
      "review screenshot 1",
      "review 2",
      "poster name 2",
      "call out 2",
      "project address 2",
      "listing url 2",
      "review screenshot 2",
      "project showcase URL 1",
      "project photo 1 ",
      "caption 1",
      "project showcase URL 2",
      "project photo 2 ",
      "caption 2",
      "packages title ",
      "packages description",
      "wood package rendering 1",
      "wood package rendering 2",
      "wood package rendering 3",
      "wood package rendering 4",
      "wood package 1",
      "wood pkg description 1 ",
      "wood package 2",
      "wood pkg description 2",
      "wood package 3",
      "wood pkg description 3",
      "wood package 4",
      "wood pkg description 4",
      "vinyl package rendering 1",
      "vinyl package rendering 2",
      "vinyl package rendering 3",
      "vinyl package rendering 4",
      "vinyl package 1",
      "vinyl pkg description 1",
      "vinyl package 2",
      "vinyl pkg description 2",
      "vinyl package 3",
      "vinyl pkg description 3",
      "vinyl package 4",
      "vinyl pkg description 4",
      "chain link package rendering 1",
      "chain link package rendering 2",
      "chain link package rendering 3",
      "chain link package 1",
      "chain link pkg description 1",
      "chain link package 2",
      "chain link pkg description 2",
      "chain link package 3",
      "chain link pkg description 3",
      "box wire package rendering 1",
      "box wire package rendering 2",
      "box wire package rendering 3",
      "box wire package rendering 4",
      "box wire package 1",
      "box wire pkg description 1",
      "box wire package 2",
      "box wire pkg description 2",
      "box wire package 3",
      "box wire pkg description 3",
      "box wire package 4",
      "box wire pkg description 4",
      "regulations title",
      "regulations description",
      "regulations PDF ",
      "regulations JPG",
      "fence regulation link",
      "front yard",
      "side yard",
      "rear max height",
      "setback",
      "corner lot rules",
      "blog url 1",
      "blog img 1",
      "blog description 1",
      "blog url 2",
      "blog img 2",
      "blog description 2",
      "blog url 3",
      "blog img 3",
      "blog description 3"
    ],
    [
      "",
      "C13 - Fencing",
      "C27 - Landscaping",
      "C8 - Concrete",
      "https://www2.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=1040925",
      "Fence",
      "Santa Clara County",
      "Palo Alto",
      "CA",
      "The best {product} installation company in {city} ",
      "For all of your fence projects large or small in Palo Alto, Ergeon is the best choice!",
      "Build a free custom quote online!",
      "Conduct virtual onsite visits to take away unnecessary time and hassle.",
      "Our skilled team of local contractors will be there to give you a masterfully crafted new fence.",
      "(408) 495-2671",
      "4.5 rating\n38 reviews",
      "4.8 rating\n2127 reviews",
      "4.85 rating\n441 reviews",
      "4.5 rating\n156 reviews",
      "A Rating",
      "Ergeon replaced a back fence for us. They have great quote building tool, where you can select all the fence type. The price was competitive with other quote, but quality of service and customer care was exceptional - they communicate everything effectively, were super punctual and work was done quickly.",
      "Roman K.",
      "They have great quote building tool and the quality of service and customer care was exceptional ",
      "Terra Villa Avenue, Palo Alto",
      "https://www.yelp.com/biz/ergeon-palo-alto-3?hrid=L6KqZKyWhE1ixjZwAq0dgg&utm_campaign=www_review_share_popup&utm_medium=copy_link&utm_source=(direct)",
      "https://drive.google.com/file/d/15m7IzeFsr62MAyS6F3lyHkkDr31yQp-p/view?usp=sharing",
      "Ergeon removed an existing 72’ wood fence and replaced with a new one. The fence is well constructed and quite attractive. The cost was very competitive with a number of other bids I received. All of the Ergeon personnel with whom I dealt were professional and friendly. I would strongly recommend hiring Ergeon for any fence construction project. ",
      "Richard N.",
      "I would strongly recommend hiring Ergeon for any fence construction project.",
      "Torwood Ct, Los Altos",
      "https://www.google.ca/search?q=Ergeon+Fences+and+Driveways&ludocid=6275209574014286638&lsig=AB86z5W1f_xwgMoFnd_GfW3oDZhL#fpstate=lie&lrd=0x808fbbcd309c2f81:0x571605dc2e407b2e,1,,,",
      "https://drive.google.com/file/d/1dTBcN6OVCLNz3zT6wm3XQo6bV01SKY9p/view?usp=sharing",
      "https://www.ergeon.com/projects-gallery/projects/driveway-installation-in-palo-alto-ca-northern-california-san-jose-palo-alto-70633",
      "https://drive.google.com/file/d/1Td-Be_hmCJX27qmLx3I3VeMXJw2mgoac/view?usp=sharing",
      "Picture Frame Side by Side With Diagonal Lattice Fence",
      "https://www.ergeon.com/projects-gallery/projects/fence-and-gate-installation-in-palo-alto-ca-northern-california-san-jose-palo-alto-73566",
      "https://drive.google.com/file/d/1988gknz_w12C02zStHFvQvTKfUu35ebi/view?usp=sharing",
      "Nail Up Dog Ear Fence With Gate",
      "Our {city} {product} Packages",
      "Choose the most popular fence package in your area",
      "https://drive.google.com/file/d/1K7Wk7p-pYD89oDC5cpEmUQWYcY3GdE1n/view?usp=sharing",
      "https://drive.google.com/file/d/1MPv1lX4gtllNgavFQmG_QwU_SwUAyT7g/view?usp=sharing",
      "https://drive.google.com/file/d/1L9anMOda0MrvnLwjLijKxPUe5fk32M8n/view?usp=sharing",
      "",
      "Premium - Flat Top",
      "Nail Up 1\" x 8\" Flat Top Redwood Con Common Pickets, Side by Side, 4\" x 4\" PT Posts",
      "Nail Up - Horizontal",
      "Nail Up 1\" x 8\" Flat Top Redwood Con Common Pickets, Horizontal, 4\" x 4\" PT Posts",
      "Picture Frame",
      "Picture Frame 1\" x 8\" Flat Top Redwood Con Common Pickets, Board on Board, 8\" PT Kickboard, 4\" x 4\" PT Post",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "https://drive.google.com/file/d/1Z872D3vqeZSRbrwewkId11qBD2ZaNAqo/view?usp=sharing",
      "https://drive.google.com/file/d/1nzyncXknEpX_w7AVe3a7q-O8O9zHd7qr/view?usp=sharing",
      "https://drive.google.com/file/d/16hDSZgW4VRMX88J1G7J12Zwv1mUIIhG4/view?usp=sharing",
      "Standard",
      "2\" Openings 11 ga. Galvanized Steel Fabric, 1 5/8 16 ga. Top Rail, 1 7/8, 16 ga. Line Post, 2 3/8, 16 ga. Terminal Post",
      "Small Commercial",
      "2\" Openings 9 ga. Galvanized Steel Fabric, 1 5/8 16 ga. Top Rail, 1 7/8, 14 ga. Line Post, 2 3/8, 14 ga. Terminal Post",
      "Large Commercial",
      "2\" Openings 9 ga. Galvanized Steel Fabric, 1 5/8 16 ga. Top Rail, 1 7/8, Sch20 Line Post, 2 3/8, Sch20 Terminal Post",
      "https://drive.google.com/file/d/1A1T9JeaU8p6YYrqqWIUF_aSMKrXXys15/view?usp=sharing",
      "https://drive.google.com/file/d/1flny4XLVyCYo27jGoO-QagcgFPrZRJ_n/view?usp=sharing",
      "https://drive.google.com/file/d/1wvCXuXpKJyLBOky7iNZqunQNWcIMgW0P/view?usp=sharing",
      "https://drive.google.com/file/d/1LbgYXMkI2VjL3ncJCPQ3u9ZkVEbGwboe/view?usp=sharing",
      "Deer Fence",
      "Box Wire PT Frame, Welded Wire 14 ga. Galvanized Steel Fabric, 4\" x 4\" PT Post ",
      "Hog Wire",
      "Box Wire Redwood Con Common Frame, Welded Wire 6 ga. Powder Coated Steel Fabric, 2” × 8” PT Kickboard, 4\" x 4\" PT Post ",
      "Top Deer Fence",
      "Box Wire Redwood Con Common Frame, Welded Wire 14 ga. Galvanized Steel Fabric, 2” × 12” PT Kickboard, 4\" x 4\" PT Post ",
      "T-Post",
      "Welded Wire 14 ga. Galvanized Steel Fabric, Steel T-post ",
      "Permits & Regulations",
      "See the {Product} Permits & Regulations for {City}",
      "UPDATED_Palo Alto Diagram",
      "Palo Alto_SantaClara_Reglations_2022",
      "Palo Alto - City Regulation",
      "4 feet, or 6 feet on properties having street frontage on University Avenue, between Middlefield Road and the eastern city limit (see Ordinance for special Regulations on this area)",
      "4 feet within street side setback, 6 feet beyond street side setback, 7 feet interior side yard",
      "7 feet",
      "no setbacks specific to fence",
      "3 feet max height above the adjacent curb grade on 35 feet Visibility Triangle Area measured from the curblines",
      "https://www.ergeon.com/blog/post/what-you-need-to-know-about-california-fence-laws\n",
      "https://drive.google.com/file/d/1C4Py70nzM_6tt5fw2B7NjHhb6lxnker3/view?usp=sharing",
      "If you’re looking to get a new fence in California, it’s important to know about the laws surrounding fences and home improvement projects. Our post will go over some important things to keep in mind.",
      "https://www.ergeon.com/blog/post/why-you-should-always-use-a-licensed-fence-contractor",
      "https://drive.google.com/file/d/1YMuv2PWFZkdLZ059y8j_343qtakP2fz6/view?usp=sharing",
      "When it’s time to get a new fence it’s important to always use a reputable, licensed, and insured contractor. Some people try to cut costs by using unlicensed contractors, but this can end up being a major issue if any problems happen during the installation or down the line. In this post, we’ll go over the main reasons why you should always use a licensed and insured fence contractor.",
      "https://www.ergeon.com/blog/post/chain-link-vs-wood-fence-style-pros-and-cons",
      "https://drive.google.com/file/d/1egJIFtfUoXdwPwd4UyD7IgyYj9BURtMs/view?usp=sharing",
      "There’s a lot to consider when weighing the pros and cons of a wood fence versus a chain link fence. We’ve tried to make the process easier for you by diving deeper into some of the areas of consideration."
    ],
    [
      "4188 Denker Ave Los Angeles, CA 90062",
      "C13 - Fencing",
      "C27 - Landscaping",
      "C8 - Concrete",
      "https://www2.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=1040925",
      "Fence",
      "Los Angeles County",
      "Los Angeles",
      "CA",
      "The best {product} installation company in {city} ",
      "Trusted {product} repair and replacement with 2000+ reviews (4.8 rating)",
      "FREE custom quote and video call for your onsite visit",
      "Fast, responsive & friendly service",
      "Transparent pricing and top notch craftsmanship",
      "(626) 873-8531",
      "4.5 rating\n38 reviews",
      "4.8 rating\n2127 reviews",
      "4.85 rating\n441 reviews",
      "4.5 rating\n156 reviews",
      "A Rating",
      "This was a first class experience. To start, their unofficial estimate on the web site before any contact was very accurate. Not many contractors will give you an accurate price on their web. Alan and Jorge managed the project with total professionalism, making sure everything went smoothly and that I was completely satisfied. Installation day went perfectly. The crew showed up on time, quickly demolished the old fence and proceeded with the installation of the new fence. Fence looks beautiful!",
      "Eric H.",
      "This was a first class experience. The fence looks beautiful!",
      "252nd Street, Harbor City",
      "https://www.yelp.com/biz/ergeon-los-angeles?hrid=Xv84iBusu-hpZM_yDmFydA&utm_campaign=www_review_share_popup&utm_medium=copy_link&utm_source=(direct)",
      "https://drive.google.com/file/d/14VaLYoyB-VGzMf51dUJmDF7fJkxwcRbo/view?usp=sharing",
      "My experience with Ergeon was very positive. From the start the follow through was good, with Matias very friendly",
      "Ana R.",
      "My experience with Ergeon was very positive.",
      "W. 54th Street, Los Angeles",
      "https://g.page/r/CeNM4Uv_YDarEBA",
      "https://drive.google.com/file/d/13la05-VP42Js-Gak4dNAQVQw9u9fGctS/view?usp=sharing",
      "",
      "https://drive.google.com/file/d/1gS7xIeqdpjaRX9A5MpU4Zla-EgMXW1Xl/view?usp=sharing",
      "Picture Frame Board on Board Fence",
      "",
      "https://drive.google.com/file/d/1Zicvn9vH-sfte6Zjz0L1Ai0hkU6HfKvf/view?usp=sharing",
      "Double Vinyl Gate",
      "Our {city} {product} Packages",
      "Choose the most popular fence package in your area",
      "https://drive.google.com/file/d/16_4D_bvyUsASiTCPbM1awpmfgNzEF4wL/view?usp=sharing",
      "https://drive.google.com/file/d/1e3lgcDxS49InJjTP3u5E7sfJdrt3JdmF/view?usp=sharing",
      "https://drive.google.com/file/d/1c-VAEZsEJiv5x7nPartBILoyt8-VM5LZ/view?usp=sharing",
      "",
      "Value - Dog Ear",
      "Nail Up 1\" x 6\" Dog Ear Cedar Pickets, Side by Side, 4\" x 4\" PT Post",
      "Decorative - Cap Rail",
      "Cap and Rail 1\" x 6\" Flat Top Cedar Pickets, Side by Side, Top and Bottom Fascia, 4\" x 4\" PT Post",
      "Nail Up - Horizontal",
      "Nail Up 1\" x 6\" Flat Top Cedar Pickets, Horizontal, 4\" x 4\" PT Posts",
      "",
      "",
      "https://drive.google.com/file/d/1X7Kx406FM1cBenY7eS2BlOxEAKlPQsqD/view?usp=sharing",
      "https://drive.google.com/file/d/1ptwDd8ucN_61_TYmDPBfzW7D0WDbmgxP/view?usp=sharing",
      "https://drive.google.com/file/d/1O0Lo44FJzC8xboEtqk7LY_pfwMxljDff/view?usp=sharing",
      "https://drive.google.com/file/d/1X_kiX35-O8TO3cENYfblekzG5zUsKD2u/view?usp=sharing",
      "Solid Privacy",
      "7/8\" x 6\" Tongue & Groove Boards, 2 Rails 1.75\" x 5.5\", 1 Metal Bottom Rail Stiffener, 5\" x 5\" Post",
      "Closed Picket",
      "7/8\" x 3\" Pickets Side by Side w/ Gaps, 2\" x 3.5\" Rails, 1 Metal Bottom Rail Stiffener,  5\" x 5\" Post",
      "Privacy w/ Diagonal Lattice",
      "7/8\" x 6\" Tongue & Groove Boards, 3 Rails 1.75\" x 5.5\", 1 Metal Bottom Rail Stiffener, Diagonal Lattice,  5\" x 5\" Post",
      "Ranch",
      "2-Rail - 3' Finish Height (Gaps are 9 1/2’’), 3-Rail - 4.5' Finish Height (Top Gaps are 10 1/2’’ and the Bottom Gap is 8 1/2’’), 4-Rail - 5' Finish Height  (Gaps are 12 1/2'') 5\" x 5\" Posts",
      "https://drive.google.com/file/d/1Z872D3vqeZSRbrwewkId11qBD2ZaNAqo/view?usp=sharing",
      "https://drive.google.com/file/d/1nzyncXknEpX_w7AVe3a7q-O8O9zHd7qr/view?usp=sharing",
      "https://drive.google.com/file/d/16hDSZgW4VRMX88J1G7J12Zwv1mUIIhG4/view?usp=sharing",
      "Standard",
      "2\" Openings 11 ga. Galvanized Steel Fabric, 1 5/8 16 ga. Top Rail, 1 7/8, 16 ga. Line Post, 2 3/8, 16 ga. Terminal Post",
      "Small Commercial",
      "2\" Openings 9 ga. Galvanized Steel Fabric, 1 5/8 16 ga. Top Rail, 1 7/8, 14 ga. Line Post, 2 3/8, 14 ga. Terminal Post",
      "Large Commercial",
      "2\" Openings 9 ga. Galvanized Steel Fabric, 1 5/8 16 ga. Top Rail, 1 7/8, Sch20 Line Post, 2 3/8, Sch20 Terminal Post",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Permits & Regulations",
      "See the {Product} Permits & Regulations for {City}",
      "Los Angles_City_LACounty_Regulations_2021",
      "Los Angeles_LosAngeles_Regulations_2022",
      " Los Angeles_City Regulation",
      "3.5 feet for R/RW zone, 6 feet for A/RA zone, and up to 8 feet with zoning approval ",
      "3.5 feet on street side within 5 feet setback on reverse corner lots in R Zones, 6 feet if lot width < 40 feet or Hillside for A / RA / R  zones, 8 feet if lot width > 40 feet for A / RA / R  Zones.                                                                                                                                                                        ",
      " 6 feet when lot width < 40 feet or Hillside, 8 feet  when lot width > 40 feet for A / RA / R  zones ",
      "5 feet street side on reverse corner lots for R Zones, 3.5 feet street side on any corner lot for RW zone  ",
      "Max 3.5 feet on Visibility Triangle Area (45 feet from the point of intersection of the extended curb lines or edges of roadway)",
      "https://www.ergeon.com/blog/post/what-you-need-to-know-about-california-fence-laws\n",
      "https://drive.google.com/file/d/1C4Py70nzM_6tt5fw2B7NjHhb6lxnker3/view?usp=sharing",
      "If you’re looking to get a new fence in California, it’s important to know about the laws surrounding fences and home improvement projects. Our post will go over some important things to keep in mind.\n",
      "https://www.ergeon.com/blog/post/why-you-should-always-use-a-licensed-fence-contractor",
      "https://drive.google.com/file/d/1YMuv2PWFZkdLZ059y8j_343qtakP2fz6/view?usp=sharing",
      "When it’s time to get a new fence it’s important to always use a reputable, licensed, and insured contractor.  In this post, we’ll go over the main reasons why you should always use a licensed and insured fence contractor.",
      "https://www.ergeon.com/blog/post/vinyl-fence-pros-and-cons",
      "https://drive.google.com/file/d/1iquiExvefhV4AC3uQar6mPyzx4ZlGSIy/view?usp=sharing",
      "When it’s time to replace your fence, you may be asking yourself what fence style is best for you and your property."
    ]
  ];

  it('should parse cities data', () => {
    const sheet = {data: {values: citiesTestData}};

    expect(parseSheet(sheet, mapping.city)).toMatchSnapshot();
    expect(parseSheet(sheet, mapping.product)).toMatchSnapshot();
  });
});
