# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.12-node

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: |
            pip install awscli
            sudo npm install -g @sentry/cli --unsafe-perm
            echo "//npm.ergeon.in/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            make install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-dependencies-{{ checksum "package.json" }}

      - when:
          condition:
            equal: [ "$BUILD_TYPE", "sitemap-only" ]

          steps:
            - run:
                name: Deploy sitemaps
                command: |
                  if [ "$CIRCLE_BRANCH" = "develop" ]; then make deploy-only-sitemap-staging; fi
                  if [ "$CIRCLE_BRANCH" = "master" ]; then make deploy-only-sitemap-production; fi

      - unless:
          condition:
            equal: [ "$BUILD_TYPE", "sitemap-only" ]

          steps:
            - run:
                name: Run Linters
                command: |
                  make lint

            - run:
                name: Run Tests and Coverage
                command: |
                  make coverage

            - deploy:
                name: Deploy
                command: |
                  if [ "$CIRCLE_BRANCH" = "develop" ]; then make deploy-staging; fi
                  if [ "$CIRCLE_BRANCH" = "master" ]; then make deploy-production; fi
